{"time":"2025-05-31T13:26:02.3361047+08:00","level":"INFO","msg":"using version","core version":"0.18.3"}
{"time":"2025-05-31T13:26:02.3361047+08:00","level":"INFO","msg":"created symlink","path":"E:\\Desktop\\Documents\\Git\\minimind\\trainer\\wandb\\run-20250531_132602-4porf6s3\\logs\\debug-core.log"}
{"time":"2025-05-31T13:26:02.3373526+08:00","level":"ERROR","msg":"dialing: google: could not find default credentials. See https://cloud.google.com/docs/authentication/external/set-up-adc for more information"}
{"time":"2025-05-31T13:26:02.9930094+08:00","level":"INFO","msg":"created new stream","id":"4porf6s3"}
{"time":"2025-05-31T13:26:02.9935464+08:00","level":"INFO","msg":"stream: started","id":"4porf6s3"}
{"time":"2025-05-31T13:26:02.9935464+08:00","level":"INFO","msg":"writer: Do: started","stream_id":{"value":"4porf6s3"}}
{"time":"2025-05-31T13:26:02.9935464+08:00","level":"INFO","msg":"handler: started","stream_id":{"value":"4porf6s3"}}
{"time":"2025-05-31T13:26:02.9935464+08:00","level":"INFO","msg":"sender: started","stream_id":{"value":"4porf6s3"}}
{"time":"2025-05-31T13:26:24.0530038+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-31T13:26:47.1590417+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-31T13:27:12.2752563+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-31T13:27:19.1886017+08:00","level":"INFO","msg":"stream: closing","id":"4porf6s3"}
